version: '3'
services:
  mdata-worker:
    build: ./app/worker
    env_file: "mdata.env"
    ports:
      - "9229:9229"
  mdata-web:
    build: ./app
    env_file: "mdata.env"
    ports:
      - "3000:3000"
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
  neo4j:
    image: neo4j:3.5.12
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
      - ./data:/data
